### ISSUE TITLE
Extra slash at the end of the url

### ISSUE THREAD

**Issue by vg1ne** [johnpapa/angular-ngrx-data#202] opened 2018-11-09 20:43 UTC
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
```

### Minimal steps to reproduce
>
buildings.metadata.ts
```typescript
import { EntityMetadataMap } from 'ngrx-data';

const entityMetadata: EntityMetadataMap = {
    Building: {},
};

const pluralNames = { Building: 'buildings' };

export const buildingsEntityConfig = {
    entityMetadata,
    pluralNames
};
```
buildings-data.module.ts
```typescript
const defaultDataServiceConfig: DefaultDataServiceConfig = {
    root: 'api/v2.1',
    timeout: 5000, // request timeout
}

@NgModule({
    imports: [
        CommonModule,
        NgrxDataModule.forRoot(buildingsEntityConfig),
    ],
    providers: [{provide: DefaultDataServiceConfig, useValue: defaultDataServiceConfig}]
})
```
buildings.service.ts
```typescript
@Injectable({
    providedIn: 'root'
})
export class BuildingService extends EntityCollectionServiceBase<Building> {
    constructor(serviceElementsFactory: EntityCollectionServiceElementsFactory) {
        super('Building', serviceElementsFactory);
    }
}
```
some.component.ts
```typescript
export class SomeComponent {
 constructor(private entityServices: EntityServices) {
        this.buildingService = this.entityServices.getEntityCollectionService('Building');
        const buildings$ = this.buildingService.getAll()
        const someBuilding$ = this.builginsService.getByKey(5)
}
```
### Any log messages given by the failure
> requested url is `/api/v2.1/buildings/`

### Expected/desired behavior
> expected url  is`/api/v2.1/buildings` (no extra slash)

### OS and Version?
> Windows 10

### Versions
>
```json
"ngrx-data": {
      "version": "6.1.0-beta.2",
      "resolved": "https://registry.npmjs.org/ngrx-data/-/ngrx-data-6.1.0-beta.2.tgz",
      "integrity": "sha512-OFUbzz7sf2saMHlrCnJsN7ub0c2O6WcK58VcJrcV/XXD4n9LAPI8r6qklxk8YVorfp6A2cAVH2jkawa9whMj6Q==",
      "requires": {
        "tslib": "^1.9.0"
      }
    },
```

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jgutix** [comment] 2018-11-14 00:15
I'd like a global way to do this, because right now in order to change this behavior, I need to create an `<Entity>DataService` for every entity like this:

First in `entity-store.module.ts` for `DataServiceConfig` within `entityHttpResourceUrls` I define the entity urls like this:

```
Order: {
        // You must specify the root as part of the resource URL.
        entityResourceUrl: `${env.api}/orders/`,
        collectionResourceUrl: `${env.api}/orders`
      },
```   

Then the dataService service is like this:

```

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import {
  DefaultDataService,
  HttpUrlGenerator,
  Logger, QueryParams
} from 'ngrx-data';

import { Observable } from 'rxjs';
import {Order} from '../../core/model/order';
import {map} from 'rxjs/operators';

@Injectable()
export class OrderDataService extends DefaultDataService<Order> {
  constructor(
    http: HttpClient,
    httpUrlGenerator: HttpUrlGenerator,
    logger: Logger
  ) {
    super('Order', http, httpUrlGenerator);
    logger.log('Created custom Order EntityDataService');
  }

  add(entity: Order): Observable<Order> {
    const entityOrError = entity || new Error(`No "${this.entityName}" entity to add`);
    return this.execute('POST', this.entityUrl.slice(0, this.entitiesUrl.length), entityOrError);
  }
}
```

And then back to the `entity-store.module.ts` need to reference this class another tree times, like this:
```
@NgModule({
  imports: [
    NgrxDataModule.forRoot({
      entityMetadata,
      pluralNames
    })
  ],
  providers: [
      AppEntityServices,
      { provide: EntityServices, useExisting: AppEntityServices},
      { provide: DefaultDataServiceConfig, useValue: getDefaultDataServiceConfig() },
      OrderDataService,
      .
      .
      .
    ],
  declarations: []
})
export class EntityStoreModule {
  constructor(entityDataService: EntityDataService,
              orderDataService: OrderDataService,
              .
              .
              .
  ) {
    entityDataService.registerService('Order', orderDataService);
    .
    .
    .
  }
}
```

As you can see @mantainers, there's a lot of boilerplate added for a simple behavior, so please, could you give us a way to change it in a single place?

**Comment by wardbell** [comment] 2018-11-21 04:42
I _think_ you're saying that the `DefaultDataService` adds a trailing slash when it sends a request to the server. 

More precisely, it adds a trailing slash for the `getAll` request (e.g, `~/api/heroes/` or, in your case, /api/v2.1/buildings/).  It doesn't do that for the other HTTP requests (e.g, ~/api/hero/42`).

Most servers do not care about that trailing slash. No one has complained before. But if it is a problem for you, there is a much easier fix.

Look at the source for `HttpUrlGenerator` (`http-url-generator.ts`). That's an abstract class whose `collectionResource(entityName: string, root: string): string;` method will interest you. That's the method that produces the URL when you're constructing a URL targeting the entire collection (such as `getAll` and `getWithQuery`.

The concrete implementation is `DefaultHttpUrlGenerator`. That's where you'll find the trailing slash.

I can't change that. It's not a bug and changing it might break others.

But you can provide an alternative implementation of `DefaultHttpUrlGenerator` (`MyHttpUrlGenerator`) that implements that method as you prefer. Provide your version as follows:
```
{provide: HttpUrlGenerator, useClass: MyHttpUrlGenerator}
```
and you'll have fixed the problem for your application.

Had that been insufficient, I would have subclassed the entire `DefaultDataService` with the fix and provided an alternative to `DefaultDataServiceFactory` that created instances of your subclass rather than of `DefaultDataService<T>`.

Or maybe I would have simply adjusted the URL with an Angular `HttpInterceptor`.

Just about _anything_ would have been better than the difficult route you took.

I'm going to close this issue because I don't think there's anything for me to change. I'm hopeful that the advice here will see you through.

If you disagree, please create a new issue, referencing this one and I'll re-examine.

Thanks for using ngrx-data.

**Closed by wardbell** 2018-11-21 04:42 UTC

**Comment by andreaswarnaar** [comment] 2018-12-04 20:36
Replacing the HttpUrlGenerator fixed my issue.
